### ISSUE TITLE
Question about Batch UV Map Generation

### ISSUE THREAD

**Issue by KeepPushingDev** [twowwj/UVMap-ID#1]
I'm working with your implementation of UV position maps for 3D point clouds. I understand the process involves mapping 3D points to 2D UV space, then encoding 3D position data for each UV location.
Question
Could you please clarify the method used for batch generation of UV maps?

Are you using any specific software for this step?
Or is it implemented through a Python algorithm?

If it's a Python algorithm, could you provide some insights into its implementation or point me to the relevant part of the codebase?
Purpose
Understanding this would greatly help in scaling up the process for larger datasets and potentially optimizing the workflow.
Thank you for your time and assistance!

**Comment by zhangqianhui** [comment]
human uv map is defined by smpl, you check the details of smpl_uv.obj file. You can download it from smpl website.
